name: "Run Build Test"
on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile*'
      - 'Dockerfile-*'
      - 'frontend/package.json'
      - 'frontend/yarn.lock'
      - 'backend/**'
      - 'frontend/src/**'
      - '**/pom.xml'
      - 'entrypoint.sh'
      - 'config/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [chen]
        version: [v3.10.17]
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    - name: Prepare Build
      run: |
        sed -i 's@registry.npmmirror.com@registry.yarnpkg.com@g' frontend/yarn.lock
        sed -i 's@^FROM registry.fit2cloud.com/jumpserver@FROM ghcr.io/jumpserver@g' Dockerfile

    - name: Build CE Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        file: Dockerfile
        tags: ghcr.io/jumpserver/${{ matrix.component }}:${{ matrix.version }}-ce
        platforms: linux/amd64
        build-args: |
          VERSION=${{ matrix.version }}
          VCS_REF=${{ github.sha }}
          APT_MIRROR=http://deb.debian.org
          NPM_REGISTRY=https://registry.yarnpkg.com
        outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
        cache-from: type=gha
        cache-to: type=gha,mode=max
